baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = 'Python/Django Developer'
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/utkucanbykl"
  [[params.social]]
    name = "github"
    url  = "https://github.com/utkucanbykl"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/utkucanbiyikli"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/7437136/utkucan-b%c4%b1y%c4%b1kl%c4%b1"
  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"

[languages]
  [languages.en]
    title = "Utkucan Bıyıklı"
    subtitle = "Backend Developer"
    keywords = "Django, Python"
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/etc/utkucan"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"


[taxonomies]
  tag      = "tags"
  category = "categories"
